
replicaCount: 2
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "13724795877"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


service:
  type: ClusterIP
  port: 80

resources: {}
 
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

