apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  user-database-name: {{ .Values.mongodbConfig.userDatabaseName }}
  product-database-name: {{ .Values.mongodbConfig.productDatabaseName }}
