apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  user-service-uri: {{ .Values.mongodbSecrets.userServiceUri }}
  product-service-uri: {{ .Values.mongodbSecrets.productServiceUri }}
