apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  user-service-uri: {{ .Values.mongodbConfig.userServiceUri }}
  product-service-uri: {{ .Values.mongodbConfig.productServiceUri }}