apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  user-service-uri: bW9uZ29kYitzcnY6Ly92aXB1bDEyMzpEZXZvcHMxMjNAY2x1c3RlcjAuMHpvY3djay5tb25nb2RiLm5ldC8=  # base64 encoded
  product-service-uri: bW9uZ29kYitzcnY6Ly92aXB1bDEyMzpEZXZvcHMxMjNAY2x1c3RlcjAuMHpvY3djay5tb25nb2RiLm5ldC8=  # base64 encoded
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  user-database-name: userdb
  product-database-name: productdb
