apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  user-service-uri: mongodb+srv://vipul123:Devops123@cluster0.0zocwck.mongodb.net/  # base64 encoded
  product-service-uri: mongodb+srv://vipul123:Devops123@cluster0.0zocwck.mongodb.net/  # base64 encoded
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  user-database-name: userdb
  product-database-name: productdb
