apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 3001
  type: {{ .Values.service.type }}