replicaCount: 2
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "13725392876"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# serviceMonitor:
#   enabled: true
#   path: /metrics # Your microservices must expose /metrics endpoint
#   interval: 15s
#   labels:
#     release: prometheus

service:
  type: ClusterIP
  port: 80

resources: {}

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 40
  # targetMemoryUtilizationPercentage: 80
