name: CI

on:
  push:
    branches:
      - main
    ignore:
      - "*/k8s/*"
      - "*/kubernetes/"
      - "*/helm/*"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push User Service
        uses: docker/build-push-action@v4
        with:
          context: ./user-service
          file: ./user-service/dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/user-service:${{github.run_id}}

      - name: Build and push Product Service
        uses: docker/build-push-action@v4
        with:
          context: ./product-service
          file: ./product-service/dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/product-service:${{github.run_id}}

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }} # Ensure correct permissions

      - name: Update image tag in Helm charts
        run: |
          sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/microservices-app/charts/user-service/values.yaml
          sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/microservices-app/charts/product-service/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "gaikwadvipul196@gmail.com"
          git config --global user.name "Vipul Gaikwad"
          git add helm/microservices-app/charts/user-service/values.yaml helm/microservices-app/charts/product-service/values.yaml
          git commit -m "Update image tags to ${{ github.run_id }}" || echo "No changes to commit"
          git push origin HEAD:main  # Ensure pushing to the correct branch
