name: CI

on:
  push:
    branches:
      - main
    ignore:
      - '*/k8s-*'
      - '*/kubernetes-*'
      - '*/helm-*'

jobs:
  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push User Service
      uses: docker/build-push-action@v4
      with:
        context: ./user-service
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest
    
    - name: Build and push Product Service
      uses: docker/build-push-action@v4
      with:
        context: ./product-service
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/product-service:latest